### ISSUE TITLE
Organization breadcrumb missing organization name

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#170]
After creating a user and adding him to an organisation via the organisation manage screen, the path shown on screen does not look right

It shows Organizations // Manage

![image](https://cloud.githubusercontent.com/assets/7315913/4205246/91d191ea-383e-11e4-9c80-6595ee349a8f.png)

**Comment by amercader** [comment]
Fixed now

**Comment by Nithyavasudevan** [comment]
this needs to be fixed for all scenarios. when add user fails on the platform for some reason, this seems broken again.
![image](https://cloud.githubusercontent.com/assets/7315913/4217601/a5371862-38e9-11e4-8007-fc631a775df8.png)

**Comment by mcginns** [comment]
This still shows Organisations // Manage when add member operation fails.

![image](https://cloud.githubusercontent.com/assets/7511445/4273201/ab068e6e-3ce8-11e4-8aeb-40e978274f22.png)

**Comment by Nithyavasudevan** [comment]
removed ready for testing label

**Comment by joetsoi** [comment]
https://github.com/ckan/ckan/pull/1873 for the add member case, this is the same bug as the roles disappearing and that will take time to merge to ckan, otherwise this is fixed
